[package]
name = "nu_plugin_dcm"
version = "0.1.2"
edition = "2018"
license = "MIT"
description = "A nushell plugin to parse Dicom files"
homepage = "https://github.com/realcundo/nu_plugin_dcm"
repository = "https://github.com/realcundo/nu_plugin_dcm"
readme = "README.md"
include = ["src/**/*", "LICENSE", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dicom = "0.4"
indexmap = "1.7" # to match the version from nu
itertools = "0.10"
bigdecimal = "0.2"

nu-plugin = "0.35"
nu-protocol = "0.35"
nu-source = "0.35"
nu-errors = "0.35"
nu-value-ext = "0.35"

[dev-dependencies]
nu-test-support = "0.35"
assert_matches = "1.5"


[profile.release]
lto = true
opt-level = 2
codegen-units = 1
