[package]
name = "nu_plugin_dcm"
version = "0.1.3"
edition = "2021"
license = "MIT"
description = "A nushell plugin to parse Dicom files"
homepage = "https://github.com/realcundo/nu_plugin_dcm"
repository = "https://github.com/realcundo/nu_plugin_dcm"
readme = "README.md"
include = ["src/**/*", "LICENSE", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.7" # ideally should match dicom
dicom = "0.5.0-rc.2"
indexmap = "1.7" # to match the version from nu
itertools = "0.10"
bigdecimal = "0.3"

nu-plugin = "0.44"
nu-protocol = "0.44"
nu-source = "0.44"
nu-errors = "0.44"
nu-value-ext = "0.44"

[dev-dependencies]
nu-test-support = "0.44"
assert_matches = "1.5"


[profile.release]
lto = true
opt-level = 2
codegen-units = 1
