[package]
name = "nu_plugin_dcm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dicom = "0.4"
indexmap = "1.7" # must match the one from nu
itertools = "0.10"
bigdecimal = "0.2"

nu-plugin = "0.34"
nu-protocol = "0.34"
nu-source = "0.34"
nu-errors = "0.34"
nu-value-ext = "0.34"

[profile.release]
lto = true
opt-level = 2
codegen-units = 1