[package]
name = "nu_plugin_dcm"
version = "0.1.8"
edition = "2021"
license = "MIT"
description = "A nushell plugin to parse Dicom files"
homepage = "https://github.com/realcundo/nu_plugin_dcm"
repository = "https://github.com/realcundo/nu_plugin_dcm"
readme = "README.md"
keywords = ["nu", "nushell", "dicom"]
include = ["src/**/*", "LICENSE", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.7" # ideally should match dicom
dicom = "0.5"
indexmap = "1.8" # to match the version from nu
itertools = "0.10"

nu-plugin = "0.68"
nu-protocol = { version = "0.68", features = ["plugin"]}

[profile.release]
lto = true
opt-level = 2
codegen-units = 1
